server:
  port: 7750
spring:
  application:
    name: com.economic.system.building
  # freemarker
  freemarker:
    request-context-attribute: request
    allow-request-override: false
    template-loader-path: classpath:/static
    cache: false
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
  # jpa
  jpa:
    show-sql: true
    generate-ddl: false
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#swagger
swagger:
  version: v0.0.9
# 不允许被删除的角色
roles:
  deleteDenys: ADMIN
author:
  ignoreUrls: /,/home,/index,/error,/v1/api-docs,/login,/swagger/**,/system/**,/index.**,/excel/**,/v1/security/loginFail,/v1/security/loginSuccess,/v1/security/logoutSuccess,/v2/api-docs,/v1/competence/findByCurrentUser,/v1/logRecord/getALLEnums,/v1/logRecord/getEnums,/v1/synchronousData/**

#hystrix调用方法的超时时间，默认是1000毫秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000
#调用高德地图配置
amap:
  key: 8e08a80b71bf4ca887c22bf8b923cac1

filePath:
  #fileRoot: D:/file
  imageRoot: D:/image/
  maxFileSize: 5
  #articleSavePath: D:/article/
  prefixs: jpg,gif,jpeg,png
  prefixLimit: jpg,jpeg,png,gif

