server:
  port: 7750
spring:
  application:
    name: com.example.projectdemo
  # jpa
  jpa: 
    show-sql: true
    generate-ddl: false
    database: MYSQL
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#swagger
swagger:
  version: v0.0.9
# 不允许被删除的角色
roles: 
  deleteDenys: ADMIN
author:
  ignoreUrls: /**,/home,/index,/error,/v1/api-docs,/login,/swagger/**,/ldap/security/loginFail,/ldap/security/loginSuccess,/ldap/security/logout,/v2/api-docs,/v1/competence/findByCurrentUser

#hystrix调用方法的超时时间，默认是1000毫秒
hystrix:
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 20000

---
########################## dev
spring: 
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/projectdemo?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

#图片上传保存地址
img:
  win_location: e:/images/
  linux_location: /data/test/demo

filePath:
  #fileRoot: D:/file
  imageRoot: e:/images/
  maxFileSize: 5
  #articleSavePath: D:/article/
  prefixs: jpg,gif,jpeg,png,docx,xlsx
  prefixLimit: jpg,jpeg,png,gif,docx,xlsx
